version: 2
project_name: airbridge

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: .
    binary: airbridge

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

    files:
      - README.md
      - LICENSE

    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# --- HOMEBREW (MACOS & LINUX) ---
brews:
  - repository:
      owner: batuhan0sanli
      name: homebrew-tap
      token: "{{ .Env.GH_PAT }}"
    
    name: airbridge
    homepage: "https://github.com/batuhan0sanli/airbridge"
    description: "AirBridge is a secure file transfer tool that uses RSA encryption."
    license: "MIT"
    
    install: |
      bin.install "airbridge"

# --- WINDOWS (SCOOP) ---
scoops:
  - repository:
      owner: batuhan0sanli
      name: scoop-bucket
      token: "{{ .Env.GH_PAT }}"

    name: airbridge
    homepage: "https://github.com/batuhan0sanli/AirBridge"
    description: "AirBridge is a secure file transfer tool that uses RSA encryption."
    license: "MIT"

# --- LINUX ---
nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage: https://github.com/batuhan0sanli/airbridge
    maintainer: Batuhan Sanli <batuhansanli@gmail.com>
    description: "AirBridge is a secure file transfer tool that uses RSA encryption."
    license: "MIT"
    formats:
      - deb
      - rpm